### ISSUE TITLE
About Training Dataset

### ISSUE THREAD

**Issue by LinyeLi60** [ryohachiuma/Deep-6dPose#2]
I download dataset from [here](http://ycb-benchmarks.s3-website-us-east-1.amazonaws.com/), but it dosen't look like the dataset used in generateData.py, could you please give the link of dataset?Thank you!

**Comment by ryohachiuma** [comment]
Hi, I used the same dataset as PoseCNN.
I followed the link below.
https://github.com/yuxng/PoseCNN
https://rse-lab.cs.washington.edu/projects/posecnn/
